heat_template_version: 2013-05-23

description: Deploy a CoreOS cluster that operates a Kubernetes cluster

parameters:
  kubernetes-master-count:
    description: Number of CoreOS machines to deploy as Kubernetes Master
    type: number
    default: 1
    constraints:
    - range:
        min: 1
        max: 1
      description: Must be between 1 and 1 servers.
  kubernetes-minion-count:
    description: Number of CoreOS machines to deploy as Kubernetes Minion
    type: number
    default: 2
    constraints:
    - range:
        min: 2
        max: 12
      description: Must be between 2 and 12 servers.
  key-name:
    type: string
    description: Name of key-pair to be used for compute instance
  flavor:
    type: string
    default: 2 GB Performance
    constraints:
    - allowed_values:
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.
  coreos-image:
    type: string
    description: Rackspace Cloud Servers CoreOS Alpha (399.0.0) UUID
    default: "49d299c1-aacc-40b7-9ac0-df4132b385b3"
  git-repo:
    type: string
    description: Public git repo url
    default: "https://github.com/metral/corekube.git"
  git-branch:
    type: string
    description: Git repo branch
    default: "master"

resources:

  coreos-cluster-uuid:
    type: OS::Heat::RandomString
  etcd:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key-name }
      image: { get_param: coreos-image }
      flavor: { get_param: flavor }
      name: "etcd"
      user_data_format: RAW
      config_drive: "true"
      user_data: |
        #cloud-config

        coreos:
          units:
            - name: private-etcd.service
              command: start
              content: |
                [Unit]
                After=network-online.target
                Requires=network-online.target

                [Service]
                ExecStart=/usr/bin/docker run -d --name etcd -p 4001:4001 -p 7001:7001 coreos/etcd

  master_machines:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: kubernetes-master-count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: coreos-image }
          flavor: { get_param: flavor }
          name: kuberentes-master-%index%
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                #cloud-config

                coreos:
                  etcd:
                    name: kubernetes-master-%index%
                    discovery: http://%discovery%:4001/v2/keys/_etcd/registry/%uuid%
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001

                  fleet:
                    metadata: kubernetes_role=master
                      
                  update:
                    group: alpha
                    reboot-strategy: off

                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.socket
                      command: start
                      content: |
                        [Socket]
                        # Talk to the API over a Unix domain socket (default)
                        ListenStream=/var/run/fleet.sock
                        # Talk to the API over an exposed port, uncomment to enable and choose a port
                        ListenStream=10001
                        Service=fleet.service

                        [Install]
                        WantedBy=sockets.target
                    - name: fleet.service
                      command: start
                    - name: setup-kubernetes.service
                      command: start
                      content: |
                        [Unit]
                        After=network-online.target
                        Requires=network-online.target

                        [Service]
                        WorkingDirectory=/root
                        Environment="DIR=corekube"
                        ExecStartPre=/usr/bin/rm -rf $DIR
                        ExecStartPre=/usr/bin/git clone -b %branch% %repo%
                        ExecStart=/usr/bin/bash ${DIR}/build_run.sh %branch% %count%
              params:
                "%discovery%": { get_attr: [etcd, networks, private, 0] }
                "%uuid%": { get_attr: [coreos-cluster-uuid, value] }
                "%count%": { get_param: kubernetes-master-count}
                "%repo%": { get_param: git-repo }
                "%branch%": { get_param: git-branch }

  minion_machines:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: kubernetes-minion-count }
      resource_def:
        type: OS::Nova::Server
        properties:
          key_name: { get_param: key-name }
          image: { get_param: coreos-image }
          flavor: { get_param: flavor }
          name: kuberentes-minion-%index%
          user_data_format: RAW
          config_drive: "true"
          user_data:
            str_replace:
              template: |
                #cloud-config

                coreos:
                  etcd:
                    name: kubernetes-minion-%index%
                    discovery: http://%discovery%:4001/v2/keys/_etcd/registry/%uuid%
                    addr: $private_ipv4:4001
                    peer-addr: $private_ipv4:7001

                  fleet:
                    metadata: kubernetes_role=minion

                  update:
                    group: alpha
                    reboot-strategy: off
                      
                  units:
                    - name: etcd.service
                      command: start
                    - name: fleet.service
                      command: start
              params:
                "%discovery%": { get_attr: [etcd, networks, private, 0] }
                "%uuid%": { get_attr: [coreos-cluster-uuid, value] }
