#cloud-config
write_files:
  - path: /run/get_discovery_interface_ip.sh
    permissions: '0755'
    content:
      get_file: https://raw.githubusercontent.com/DigitalPacific/corekube/master/cloud-config/get_discovery_interface_ip.sh
  - path: /run/wcnotify.sh
    permissions: '0755'
    content: 
      get_file: https://raw.githubusercontent.com/DigitalPacific/corekube/master/cloud-config/wcnotify.sh
coreos:
  update:
    group: stable
    reboot-strategy: off
  units:
    - name: private-discovery-setup.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Requires=network-online.target
        [Service]
        Type=forking
        ExecStart=/usr/bin/bash /run/get_discovery_interface_ip.sh
    - name: private-discovery.service
      command: start
      content: |
        [Unit]
        After=network-online.target private-discovery-setup.service
        Requires=network-online.target private-discovery-setup.service
        [Service]
        EnvironmentFile=/run/IP
        RestartSec=5s
        ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.11
        ExecStart=/usr/bin/docker run -d --name discovery \
          -p 2379:2379 -p 2380:2380 \
          -v /usr/share/ca-certificates/:/etc/ssl/certs \
          --net host quay.io/coreos/etcd:v2.0.11 -name discovery \
          -initial-advertise-peer-urls http://${IP}:2380,http://${IP}:7001 \
          -listen-peer-urls http://${IP}:2380,http://${IP}:7001 \
          -initial-cluster discovery=http://${IP}:2380,discovery=http://${IP}:7001 \
          -advertise-client-urls http://${IP}:2379,http://${IP}:4001 \
          -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
    - name: private-discovery-done.service
      command: start
      content: |
        # Notifiy wait condition
        [Unit]
        After=network-online.target private-discovery.service
        Requires=network-online.target private-discovery.service
        [Service]
        ExecStart=/run/wcnotify.sh
