#cloud-config
write_files:
  - path: /run/setup_etcd_cloudinit_conf.sh
    permissions: '0755'
    content: |
      #!/bin/bash

      ENV="/etc/environment"

      # Test for RW access to $1
      touch $ENV
      if [ $? -ne 0 ]; then
          echo exiting, unable to modify: $ENV
          exit 1
      fi

      # Setup environment target
      sed -i -e '/^COREOS_PUBLIC_IPV4=/d' \
          -e '/^COREOS_PRIVATE_IPV4=/d' \
          "${ENV}"

      # We spin loop until the the IP addresses are set
      function get_ip () {
          IF=$1
          IP=
          while [ 1 ]; do
              IP=$(ifconfig $IF | awk '/inet / {print $2}')
              if [ "$IP" != "" ]; then
                  break
              fi
              sleep .1
          done
          echo $IP
      }

      # Echo results of IP queries to environment file as soon as network interfaces
      # get assigned IPs
      echo COREOS_PUBLIC_IPV4=$(get_ip eth0) >> $ENV # Also assigned to same IP
      echo COREOS_PRIVATE_IPV4=$(get_ip eth0) >> $ENV #eno1 should be changed to your device name
      A=`cat /etc/environment | grep COREOS_PRIVATE_IPV4 | cut -f2 -d "="`
      sed -i "s#=:#=${A}:#g" /run/systemd/system/etcd.service.d/20-cloudinit.conf
      systemctl daemon-reload
  - path: /run/get_discovery_ip_port.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      # Sets up environment file with the discovery node's IP &
      # port so # that in Overlode's template 
      # master-apiserver@.service it can be passed 
      # in as an argument 
      /usr/bin/cat /run/systemd/system/etcd.service.d/20-cloudinit.conf | /usr/bin/grep -i discovery | /usr/bin/cut -f3 -d"=" | /usr/bin/awk -F '/v' '{print $1}' > /run/discovery_ip_port
      /usr/bin/sed -i 's/^/DISCOVERY_IP_PORT=/' /run/discovery_ip_port
coreos:
  etcd:
    name: kubernetes_master
    discovery: http://%discovery%:2379/v2/keys/discovery/%uuid%
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4
    metadata: kubernetes_role=master
  update:
    group: stable
    reboot-strategy: off
  units:
    - name: setup-etcd-cloudinit-conf.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Setup environment with private (and public) IP addresses

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/run/setup_etcd_cloudinit_conf.sh
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: get_discovery_ip_port.service
      command: start
      runtime: true
      content: |
        # Runs get_discovery_ip_port.sh to have discovery IP &
        # port ready for consumption by overlord when creating
        # the Kubernetes' master-api@.service template
        [Unit]
        After=network-online.target
        Requires=network-online.target

        [Service]
        ExecStart=/usr/bin/bash /run/get_discovery_ip_port.sh
    - name: flannel-install.service
      command: start
      content: |
        # Installs flannel
        [Unit]
        After=network-online.target
        Requires=network-online.target 

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/wget -N -P /opt/bin %flannel_url%
        ExecStart=/usr/bin/chmod +x /opt/bin/flanneld
    - name: flannel.service
      command: start
      content: |
        # Configures & starts flannel
        [Unit]
        After=network-online.target etcd.service flannel-install.service
        Requires=network-online.target etcd.service flannel-install.service

        [Service]
        ExecStartPre=/usr/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.244.0.0/15", "Backend": {"Type": "vxlan"}}'
        ExecStart=/opt/bin/flanneld -iface=%kubernetes_net_interface%
        Restart=always
        RestartSec=5s
    - name: flannel-env.path
      command: start
      content: |
        # Ensures flannel env vars are set to use with Docker
        [Path]
        PathExists=/run/flannel/subnet.env
        Unit=docker.service
    - name: docker.service
      command: start
      content: |
        # Starts new docker server that uses flannel 
        [Unit]
        After=flannel-env.path network-online.target flannel.service
        Requires=flannel-env.path network-online.target flannel.service
        Description=Docker Application Container Engine

        [Service]
        EnvironmentFile=/run/flannel/subnet.env
        ExecStartPre=/bin/mount --make-rprivate /
        ExecStartPre=/usr/bin/systemctl kill docker.service
        ExecStart=/usr/bin/docker -d --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}

        [Install]
        WantedBy=multi-user.target